version: '3.4'

services:
  web:
    image: 192.168.13.100:30000/manager
    build:
      context: .
      dockerfile: scripts/docker/web/prd/dockerfile
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - scripts/docker/web/prd/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=Manag3/2
      - POSTGRES_DB=manager
volumes:
  postgres_data:
  static_volume: