version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: scripts/docker/web/dev/dockerfile
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:80
    env_file:
      - scripts/docker/web/dev/.env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=manager
      - POSTGRES_PASSWORD=Manag3/2
      - POSTGRES_DB=manager_dev

volumes:
  postgres_data: