ARG base=phusion/passenger-customizable
FROM ${base} as builder

ENV CONTAINER_HOME=/home/app
CMD /sbin/my_init

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --fix-missing --no-install-recommends \
  binutils \
  python3 \
  python3-pip \
  python3-setuptools \
  git

WORKDIR $CONTAINER_HOME
RUN git clone https://github.com/abulen/manager.git

# move to app directory
WORKDIR $CONTAINER_HOME/manager/app

# install dependencies
RUN python3 -m pip install --upgrade pip && \
    sleep 5 && \
	  pip3 install -r requirements.txt

RUN python3 manage.py collectstatic --noinput

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


FROM ${base} AS runner

ENV CONTAINER_HOME=/home/app
ENV CONTAINER_PROJECT=$CONTAINER_HOME/web

CMD /sbin/my_init

RUN rm -f /etc/service/nginx/down /etc/nginx/sites-enabled/default

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --fix-missing --no-install-recommends \
  binutils \
  python3 \
  python3-pip \
  python3-setuptools

COPY --from=builder /home/app/manager/app /home/app/web
COPY --from=builder /home/app/manager/scripts/docker/web/site.conf /etc/nginx/sites-enabled/site.conf
COPY --from=builder /home/app/manager/scripts/docker/web/entrypoint.sh $CONTAINER_HOME
RUN chmod +x $CONTAINER_HOME/*.sh

# move to home Project directory
WORKDIR $CONTAINER_PROJECT
RUN python3 -m pip install --upgrade pip && \
    sleep 5 && \
	  pip3 install -r requirements.txt

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# start app
EXPOSE 80


