version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.db

volumes:
  postgres_data:
  static_volume: