ARG base=phusion/passenger-customizable
FROM ${base}

ENV HOME /root
ENV CONTAINER_HOME=/home/app
ENV CONTAINER_PROJECT=$CONTAINER_HOME/web

CMD ["/sbin/my_init"]

RUN rm -f /etc/service/nginx/down /etc/nginx/sites-enabled/default

RUN apt-get update -qq; \
    apt-get install -y --fix-missing --no-install-recommends \
        software-properties-common wget

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --fix-missing --no-install-recommends \
  binutils \
  python3 \
  python3-pip \
  python3-setuptools

ADD scripts/docker/web/site.conf /etc/nginx/sites-enabled/site.conf
COPY scripts/docker/web/dev/entrypoint.sh $CONTAINER_HOME
RUN chmod +x $CONTAINER_HOME/*.sh

# COPY project to container directory
COPY app/ $CONTAINER_PROJECT

# move to home Project directory
WORKDIR $CONTAINER_PROJECT
RUN python3 -m pip install \
         --trusted-host pypi.org \
         --trusted-host pypi.python.org \
         --trusted-host files.pythonhosted.org \
         --upgrade pip && \
    sleep 5 && \
	pip3 install \
         --trusted-host pypi.org \
         --trusted-host pypi.python.org \
         --trusted-host files.pythonhosted.org \
         -r requirements.txt

RUN python3 manage.py collectstatic --noinput

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# start app
EXPOSE 80
